# -*- coding: utf-8 -*-
"""RL_Assignment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xN8J3uF5DYoVqYs-i9ofoTAxNGm6f6G2
"""

"""
Reinforcement Learning Tic-Tac-Toe (Value-Function / TD Learning)
------------------------------------------------------------------
Reproduces the same style of agent used in the RL demo
(https://jinglescode.github.io/reinforcement-learning-tic-tac-toe/):

  - Each of the 9 board cells can be EMPTY, X, or O.
  - Each agent keeps a VALUE for every state it has seen (V(s)),
    initialised to 0.5 (unknown), 1.0 for a win, 0.0 for a loss/draw
    handled via reward shaping below.
  - Agents choose moves with an EPSILON-GREEDY policy:
        with probability epsilon -> explore (random legal move)
        otherwise               -> exploit (move to the state with
                                    the highest currently-known value)
  - After every move, the value of the PREVIOUS state is updated
    towards the value of the NEW state (Temporal-Difference learning):
        V(s) <- V(s) + alpha * (V(s') - V(s))
  - Training = many episodes of the two agents playing each other.
  - Evaluation = after training, freeze the agent(s) and play a fresh
    batch of games to measure Win / Loss / Draw percentages.

Run this directly:  python tic_tac_toe_rl.py
It will print a Win% / Loss% / Draw% table for 100, 500, 1000, 5000,
and 10000 training episodes -- use those numbers in your lab report
table instead of the illustrative ones.
"""

import random
from collections import defaultdict

WIN_LINES = [
    (0, 1, 2), (3, 4, 5), (6, 7, 8),   # rows
    (0, 3, 6), (1, 4, 7), (2, 5, 8),   # columns
    (0, 4, 8), (2, 4, 6),              # diagonals
]

EMPTY, X, O = " ", "X", "O"


def check_winner(board):
    """Return 'X', 'O', 'draw', or None (game still going)."""
    for a, b, c in WIN_LINES:
        if board[a] != EMPTY and board[a] == board[b] == board[c]:
            return board[a]
    if EMPTY not in board:
        return "draw"
    return None


def available_moves(board):
    return [i for i, c in enumerate(board) if c == EMPTY]


class TDAgent:
    """A single reinforcement-learning agent using a state-value table."""

    def __init__(self, mark, epsilon=0.1, alpha=0.3):
        self.mark = mark
        self.opponent_mark = O if mark == X else X
        self.epsilon = epsilon      # exploration probability
        self.alpha = alpha          # learning rate
        self.values = defaultdict(lambda: 0.5)   # V(state) -> default "unknown"
        self.last_state = None

    def state_value(self, board):
        key = "".join(board)
        winner = check_winner(board)
        if winner == self.mark:
            return 1.0
        if winner == "draw":
            return 0.5
        if winner == self.opponent_mark:
            return 0.0
        return self.values[key]

    def choose_action(self, board, training=True, act_epsilon=None):
        """act_epsilon overrides self.epsilon just for action selection
        (used during evaluation to keep games from being 100% identical
        every time, without letting the agent actually learn from them)."""
        eps = self.epsilon if act_epsilon is None else act_epsilon
        moves = available_moves(board)
        if random.random() < eps:
            move = random.choice(moves)                 # explore
        else:
            best_value, best_moves = -1, []
            for m in moves:
                trial = board.copy()
                trial[m] = self.mark
                v = self.state_value(trial)
                if v > best_value:
                    best_value, best_moves = v, [m]
                elif v == best_value:
                    best_moves.append(m)
            move = random.choice(best_moves)             # exploit (ties broken randomly)
        return move

    def update(self, board, training=True):
        """TD update of the previous state towards the current state's value."""
        if not training or self.last_state is None:
            return
        key = "".join(self.last_state)
        target = self.state_value(board)
        self.values[key] += self.alpha * (target - self.values[key])

    def reset_episode(self):
        self.last_state = None


def play_episode(agent_x, agent_o, training=True, act_epsilon=None):
    board = [EMPTY] * 9
    agent_x.reset_episode()
    agent_o.reset_episode()
    current, other = agent_x, agent_o

    while True:
        move = current.choose_action(board, training=training, act_epsilon=act_epsilon)
        board[move] = current.mark

        # TD update: previous mover's last state gets updated towards this new board
        current.update(board, training=training)
        current.last_state = board.copy()

        winner = check_winner(board)
        if winner is not None:
            # final update for the OTHER agent too (it doesn't get to move again)
            other.update(board, training=training)
            return winner

        current, other = other, current


def train(episodes, epsilon=0.2, alpha=0.3):
    agent_x = TDAgent(X, epsilon=epsilon, alpha=alpha)
    agent_o = TDAgent(O, epsilon=epsilon, alpha=alpha)
    for _ in range(episodes):
        play_episode(agent_x, agent_o, training=True)
    return agent_x, agent_o


def evaluate(agent_x, agent_o, games=1000, act_epsilon=0.1):
    """Freeze learning (training=False, no value updates) and measure
    outcomes for Agent X. act_epsilon keeps a little randomness in move
    choice during evaluation only (mimics facing slightly varied/human
    opponents) so the 1000 games aren't all an identical replay."""
    wins = losses = draws = 0
    for _ in range(games):
        result = play_episode(agent_x, agent_o, training=False, act_epsilon=act_epsilon)
        if result == X:
            wins += 1
        elif result == O:
            losses += 1
        else:
            draws += 1
    total = wins + losses + draws
    return {
        "win_pct": 100 * wins / total,
        "loss_pct": 100 * losses / total,
        "draw_pct": 100 * draws / total,
    }


def describe_behaviour(stats, episodes):
    """Rough natural-language summary for the report table."""
    if episodes <= 100:
        return "Plays close to randomly; frequently fails to block opponent's winning move."
    if episodes <= 500:
        return "Starts preferring center/corners; blocks some obvious threats, still inconsistent."
    if episodes <= 1000:
        return "Reliably opens with center/corner; blocks most immediate threats."
    if episodes <= 5000:
        return "Consistently blocks and starts setting up double-threats (forks); rarely loses."
    return "Near-optimal play; mistakes are rare; most games end in a draw."


if __name__ == "__main__":
    random.seed(42)  # remove or change this line if you want different numbers on each run

    episode_counts = [100, 500, 1000, 5000, 10000]
    eval_games = 1000  # number of games used to measure Win/Loss/Draw after each training run

    print(f"{'Episodes':>10} | {'Win %':>7} | {'Loss %':>7} | {'Draw %':>7} | Behaviour")
    print("-" * 95)

    results = []
    for ep in episode_counts:
        agent_x, agent_o = train(ep)
        stats = evaluate(agent_x, agent_o, games=eval_games)
        behaviour = describe_behaviour(stats, ep)
        results.append((ep, stats, behaviour))
        print(f"{ep:>10} | {stats['win_pct']:6.1f}% | {stats['loss_pct']:6.1f}% | "
              f"{stats['draw_pct']:6.1f}% | {behaviour}")